### ISSUE TITLE
deprecated prepublish

### ISSUE THREAD

**Issue by gabrielrussoc** [maratonime/simone#15]
the prepublish script on `package.json` is deprecated

`npm WARN prepublish-on-install As of npm@5,prepublishscripts are deprecated.`

look here for more
https://docs.npmjs.com/misc/scripts

**Comment by pedroteosousa** [comment]
What is your npm version?

**Comment by pedroteosousa** [comment]
We should use prepare instead of prepublish.

https://github.com/xfiveco/generator-chisel/issues/199
